### ISSUE TITLE
interested for a maintainer

### ISSUE THREAD

**Issue by ptr1337** [rkstrdee/Arch#1]
Hey,

me and some other devs are developing are new arch based os.
Are you interested to maintain the theme ? 

I really like your theme!

You can write me a email under:
ptr1337@cachyos.org

regards

**Comment by ddh4r4m** [comment]
Sure!

**Comment by ptr1337** [comment]
did you got my mail back ?

**Comment by ddh4r4m** [comment]
Nope.

**Comment by ddh4r4m** [comment]
Got it, it was in spam for some reason.
