### ISSUE TITLE
Font color used in screenshot on readme

### ISSUE THREAD

**Issue by femto-code** [rkstrdee/Arch#4]
Hi, theme is looking nice. I would like to know, which font face you used in this screenshot [here](https://camo.githubusercontent.com/0a12410bbd90f8c0ef25a202d619eee1fd3f7e3256d24aea68e65e87c45fb25d/68747470733a2f2f692e696d6775722e636f6d2f433768707635332e706e67).
Thank you.

**Comment by ddh4r4m** [comment]
Thank you, Google Sans.
